name: Deploy Code to Release Branch ðŸš€
on:
  workflow_dispatch:

jobs:
  build:
    name: Push to Release Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      # Workflow dispatch event that pushes the current version to the release branch.
      # From here the secondary production deployment workflow will trigger to build the dependencies.
      - name: Deploy ðŸš€
        uses: https://github.com/SWS01700/copy-of-group-6-project
        with:
          branch: main
          folder: Project1
          clean: false
          single-commit: true
